export const categoryList = ["E-juice", "Mods", "Atomizer", "Accessories", "Disposable Vape"];
export const brands = [
    'Oxva',
    'Salt Nic',
    'Herbz',
    'Geek Vape',
    'Wotofo',
    'Axis',
    'Drop',
    'Power Wires',
    'Lost Vape',
    'IQ',
    'Artery',
    'Pastry Vapors',
    'Flava',
    'Drip a Holic',
    'Cold Snap',
    'Master',
    'Glorian Beans',
    'Mal',
    'Classsico',
    'Kalmado',
    'Drizzle All Day',
    'Wild Drip',
    'Kings Deluxe',
    'Power Line Up',
    'Deadwood',
    'Top Fog',
    'Shift',
    'Geekvape',
    'Cigpet',
    'Boss'
];